import Link from "next/link";
import { ArrowDown, ArrowUpLeft } from "lucide-react";
import { services } from "@/data/services";
import { projects } from "@/data/projects";
import { LargeCTA, Visual } from "./sections";

export function HomeExperience(){return <>
 <section className="home-hero noise"><div className="container-wide hero-layout"><div className="hero-copy"><p className="kicker">INDEPENDENT DIGITAL STUDIO — 2026</p><h1>نصنع هويات<br/><span>تُرى وتُذكر.</span></h1><p>استوديو رقمي يبني الهويات والتجارب والمجتمعات بشخصية واضحة وتنفيذ دقيق.</p><div className="hero-actions"><Link href="/services">استعرض خدماتنا <ArrowUpLeft/></Link><Link href="/portfolio" className="quiet">شاهد أعمالنا <ArrowUpLeft/></Link></div></div><div className="hero-machine" aria-hidden><div className="machine-core"><span>PX</span><i/><b>PREXEL / CREATIVE UNIT</b></div><p>IDENTITY<br/>EXPERIENCE<br/>MOTION</p><small>DXB — 25.2048° N</small></div></div><div className="scroll-note"><ArrowDown/> مرّر للاستكشاف</div></section>
 <section className="intro-strip"><div className="container-wide"><p>من الفكرة الأولى</p><strong>نبني أنظمة بصرية<br/>تعيش عبر الشاشات.</strong><span>استراتيجية / تصميم / تطوير / حركة</span></div></section>
 <section className="home-services container-wide"><header><p className="kicker">SELECTED SERVICES</p><h2>قدرات متعددة.<br/>رؤية واحدة.</h2></header>{services.slice(0,3).map((s,i)=><article key={s.id} className={i%2?"reverse":""}><Visual label={s.visual} tone={i===1?"visual-blue":i===2?"visual-red":"visual-violet"}/><div><span className="service-no">{s.no}</span><p>{s.category}</p><h3>{s.title}</h3><p className="copy">{s.short}</p><Link href={`/services/${s.id}`}>اكتشف الخدمة <ArrowUpLeft/></Link></div></article>)}<Link className="text-link" href="/services">عرض جميع الخدمات <ArrowUpLeft/></Link></section>
 <section className="selected-work"><div className="container-wide"><header><p className="kicker">SELECTED WORK</p><h2>عملٌ يتحدث<br/>قبل أن نشرحه.</h2></header><div className="editorial-work">{projects.slice(0,3).map((p,i)=><Link href={`/portfolio/${p.id}`} key={p.id} className={`work-${i+1}`}><Visual label={`0${i+1} / ${p.client}`} tone={p.tone}/><div><span>{p.category} — {p.year}</span><h3>{p.title}</h3></div></Link>)}</div><Link className="text-link" href="/portfolio">كل الأعمال <ArrowUpLeft/></Link></div></section>
 <section className="why-prexel"><div className="container-wide"><div><p className="kicker">WHY PREXEL</p><h2>لسنا منفّذين<br/>في نهاية الطريق.<br/><span>نحن جزء من الفكرة.</span></h2></div><ol><li><span>01</span><strong>نفهم قبل أن نصمّم</strong><p>نحوّل الهدف والجمهور والسياق إلى قرار بصري واضح.</p></li><li><span>02</span><strong>نبني أنظمة، لا لقطات</strong><p>كل مخرج يعيش ضمن لغة قابلة للتوسع بعد الإطلاق.</p></li><li><span>03</span><strong>نجمع الحرفة بالتقنية</strong><p>هوية وحركة وتجربة تعمل معًا تحت اتجاه إبداعي واحد.</p></li></ol></div></section>
 <LargeCTA/>
 </>}
