"use client";
import { useState } from "react";
import { Check, ChevronLeft, ChevronRight, Upload } from "lucide-react";
const serviceOptions=["Discord","Bots","Stream Pack","Branding","3D","FiveM","Web","مشروع مخصص"];
export function ProjectForm(){
 const [step,setStep]=useState(1);const [done,setDone]=useState(false);const [service,setService]=useState("");const [budget,setBudget]=useState("");const [date,setDate]=useState("");const [error,setError]=useState("");
 const forward=()=>{if(step===1&&!service){setError("اختر نوع الخدمة للمتابعة.");return}if(step===2&&(!budget||!date)){setError("حدّد الميزانية والموعد المفضل للمتابعة.");return}setError("");setStep(step+1)};
 if(done)return <div className="success-screen"><span><Check/></span><p className="kicker">REQUEST RECEIVED</p><h2>وصلتنا فكرتك.</h2><p>سنراجع الملخص ونتواصل معك خلال يوم عمل واحد.</p><button onClick={()=>{setDone(false);setStep(1)}}>إرسال طلب آخر</button></div>;
 return <div className="project-form"><div className="form-progress"><div>{[1,2,3].map((n,i)=><span key={n} className={step>=n?"active":""}>{i>0&&<i/>}0{n}</span>)}</div><p>الخطوة {step} من 3</p></div>
 {step===1&&<section className="form-step"><header><p className="kicker">01 / SERVICE</p><h2>ما الذي سنبنيه معًا؟</h2><p>اختر المسار الأقرب. سنضبط التفاصيل لاحقًا.</p></header><fieldset><legend className="sr-only">نوع الخدمة</legend><div className="choice-grid">{serviceOptions.map((x,i)=><button type="button" className={service===x?"selected":""} onClick={()=>setService(x)} key={x}><small>0{i+1}</small>{x}</button>)}</div></fieldset>{error&&<p className="form-error">{error}</p>}<button className="form-next" onClick={forward}>الميزانية والمدة <ChevronLeft/></button></section>}
 {step===2&&<section className="form-step scope-step"><header><p className="kicker">02 / SCOPE</p><h2>لنحدّد مساحة المشروع.</h2><p>لا يلزم أن تكون الأرقام نهائية؛ نحتاج نقطة انطلاق واقعية.</p></header><div className="budget-options">{["$25 — $75","$75 — $200","$200 — $500","$500+"].map(x=><button className={budget===x?"selected":""} onClick={()=>setBudget(x)} key={x}>{x}<small>ميزانية متوقعة</small></button>)}</div><label>موعد التسليم المفضل<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" onClick={()=>setStep(1)}><ChevronRight/> السابق</button><button className="form-next" onClick={forward}>بيانات المشروع <ChevronLeft/></button></div></section>}
 {step===3&&<form className="form-step" onSubmit={e=>{e.preventDefault();setDone(true)}}><header><p className="kicker">03 / DETAILS</p><h2>أعطِ الفكرة صوتًا.</h2><p>كلما كان السياق أوضح، كانت بدايتنا أقوى.</p></header><div className="form-split"><label>الاسم الكامل<input required placeholder="اكتب اسمك"/></label><label>البريد الإلكتروني<input required type="email" placeholder="name@example.com"/></label></div><label>Discord username<input placeholder="username"/></label><label>وصف المشروع<textarea required rows={7} placeholder="الهدف، الجمهور، وما الذي تريد تغييره..."/></label><label className="upload"><Upload/><span>اسحب ملفاتك هنا أو اخترها<small>PNG, JPG, PDF — حتى 10MB</small></span><input type="file" multiple/></label><aside className="project-summary"><h3>ملخص البداية</h3><p><span>الخدمة</span>{service}</p><p><span>الميزانية</span>{budget}</p><p><span>الموعد</span>{date}</p></aside><div className="form-actions"><button type="button" onClick={()=>setStep(2)}><ChevronRight/> السابق</button><button className="form-next" type="submit">إرسال الطلب <ChevronLeft/></button></div></form>}
 </div>
}
